
CREATE TABLE GLGL_FORNECEDOR
(
ID_FORNECEDOR INT IDENTITY, NOME VARCHAR(120), CIDADE VARCHAR(50),BAIRRO VARCHAR(100),ESTADO VARCHAR(50),UF VARCHAR(2),PRODUTO VARCHAR(200),QTD VARCHAR(100),
VALOR VARCHAR(15), PRIMARY KEY (ID_FORNECEDOR))


Insert into dbo.GLGL_CLIENTES(NOME, CPF_CNPJ,CIDADE,BAIRRO,ESTADO,UF,PRODUTO,QTD,TELEFONE)
Values ('Pedro',NULL,'Cotia ','','São Paulo','SP',
'Controle PS4 Slim Preto Original',1,null);


Insert into GLGL_FORNECEDOR(NOME,CIDADE,BAIRRO,ESTADO,UF,PRODUTO,QTD,VALOR,DATE)
VALUES ('Mercado Livre','SAO PAULO',null,'SAO PAULO','SP','Fatura',1,107.69,'05/02/2024'); 

select * from GLGL_FORNECEDOR

update GLGL_FORNECEDOR set valor = 328
where ID_FORNECEDOR = 18


CREATE TABLE GLGL_PRODUTOS
(
ID_PRODUTOS INT IDENTITY, PRODUTO VARCHAR(120), QTD VARCHAR(15),CONSOLE VARCHAR(100),VALORNOVO NVARCHAR(50),VALORVENDAMARKETPLACE NVARCHAR(50),VALORUSADO NVARCHAR(50),  VALORCUSTO NVARCHAR(50),VALORVENDA NVARCHAR(50),
STATUS VARCHAR(100),OBS VARCHAR(100),GENERO VARCHAR(100),MARKETPLACE VARCHAR(100), DATACOMPRA DATE, MESDAVENDA DATE
, PRIMARY KEY (ID_PRODUTOS));

Insert into GLGL_PRODUTOS(PRODUTO,QTD,CONSOLE,VALORNOVO,VALORVENDAMARKETPLACE,VALORUSADO,VALORCUSTO,VALORVENDA,STATUS,OBS,GENERO,MARKETPLACE,DATACOMPRA,MESDAVENDA)
VALUES('World War Z',1,'PS4',100,100,80,50,100,'SEMINOVO','DISPONIVEL','ACAO','Site/Shopee/ML/OLX','30/01/2024',NULL);

