select * from glgl_clientes

Insert into dbo.GLGL_CLIENTES(NOME, CPF_CNPJ,CIDADE,BAIRRO,ESTADO,UF,PRODUTO,QTD,TELEFONE)
Values ('Valdir Lenhardt',NULL,'Camboriú','',' Santa Catarina','SC',
'Fonte do Xbox 360 versão 2015 Lacrado',1,null);

SELECT * FROM GLGL_PRODUTOS
WHERE 1=1
AND CONSOLE = 'PS3'
--AND OBS = 'DISPONIVEL'
--AND OBS = 'vendido'
--AND MARKETPLACE NOT IN ('Mercado Livre')
ORDER BY PRODUTO ASC;

UPDATE GLGL_PRODUTOS SET   --PRODUTO = 'HD Externo 1TB Henrique'
obs = 'VENDIDO', MARKETPLACE = 'Whatsapp', MESDAVENDA = '01/02/2024', VALORVENDA = 0, VALORVENDAMARKETPLACE = 0
where 1=1 
--AND OBS = 'vendido'
AND ID_PRODUTOS IN (129)
--AND MARKETPLACE NOT IN ('Mercado Livre')

Insert into GLGL_PRODUTOS(PRODUTO,QTD,CONSOLE,VALORNOVO,VALORVENDAMARKETPLACE,VALORUSADO,VALORCUSTO,VALORVENDA,STATUS,OBS,GENERO,MARKETPLACE,DATACOMPRA,MESDAVENDA)
VALUES('God Of War Ascension',1,'PS3',0,69,300,0,11.06,'Seminovo','VENDIDO','ACAO','MERCADO LIVRE','13/02/2024', '13/02/2024');


SELECT * FROM GLGL_FORNECEDOR;

delete GLGL_PRODUTOS
where ID_PRODUTOS = 137